# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: polysics.github.com
title: I Me My Mine
author: Luca Pradovera
email: lpradovera@mojolingo.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
  username: polysics

# disqus:
#   id: disqusid
